Stage2
choco-cat/Fw-framework pull request #2
Opened 2022-09-06 12:18 UTC by choco-cat

Второй этап создания fw

2022-09-06 13:53 UTC, manao-dev requested changes

2022-09-06 13:53 UTC, manao-dev commented on Fw/Core/Page.php
> +        echo "<$tag>$content</$tag>";
не совсем понимаю какую задачу мы этим хотим решать, и зачем она статическая в пэйже

2022-09-06 13:53 UTC, manao-dev commented on Fw/Core/Page.php
> +        $propertiesUnique = array_unique($this->headProperties[$key]);
нет смысла использовать array_unique в наших контейнерах. С большими массивами он работает медленно. У нас же ассоциативный массив, а в нём ключи уникальные, давай сделаем для каждого уникального элемента уникальный ключ.

2022-09-06 13:53 UTC, manao-dev commented on Fw/Core/Page.php
> +        return self::$properties[$id] ?? '';
не понимаю зачем поле $properties статичное

2022-09-06 13:59 UTC, choco-cat commented on Fw/Core/Page.php
> +        echo "<$tag>$content</$tag>";
Так она вызывается в шаблоне в header, статическая - чтобы не создавать объект для вызова. По условиям класс должен уметь вставлять тег в любое место страницы. Метод принимает название тега и его содержимое и выводит тег.

2022-09-06 14:00 UTC, choco-cat commented on Fw/Core/Page.php
> +        echo "<$tag>$content</$tag>";
> не совсем понимаю какую задачу мы этим хотим решать, и зачем она статическая в пэйже

Так она вызывается в шаблоне в header, статическая - чтобы не создавать объект для вызова. По условиям класс должен уметь вставлять тег в любое место страницы. Метод принимает название тега и его содержимое и выводит тег.

2022-09-06 14:04 UTC, choco-cat commented on Fw/Core/Page.php
> +        return self::$properties[$id] ?? '';
> не понимаю зачем поле $properties статичное

Результат экспериментов. Исправлю.

2022-09-06 14:10 UTC, choco-cat commented on Fw/Core/Page.php
> +        $propertiesUnique = array_unique($this->headProperties[$key]);
> нет смысла использовать array_unique в наших контейнерах. С большими массивами он работает медленно. У нас же ассоциативный массив, а в нём ключи уникальные, давай сделаем для каждого уникального элемента уникальный ключ.

Функцию уберу, просто проверить, содержит ли массив элемент перед добавлением. Ключи у меня уникальные для проперти, которые не в head. Для множества включаемых скриптов это элемент с ключом '#FW_Head_js#', он сам является массивом (числовым). Точно нужно делать для каждого скрипта/css-файла уникальный ключ в массиве properties?

2022-09-06 15:13 UTC, manao-dev commented on Fw/Core/Page.php
> +        $propertiesUnique = array_unique($this->headProperties[$key]);
Да, без этого есть большой шанс случайно подключить 2 раза одни и те же срипты, что вызовет дублирование при их выполнении

2022-09-06 15:17 UTC, manao-dev commented on Fw/Core/Page.php
> +        echo "<$tag>$content</$tag>";
не правильно поняли этот пункт. Этот метод точно не нужен, либо его надо очень сильно перерабатывать, потому что
- есть теги однострочные, т.е без закрвающегося блока
- у тегов есть атрибуты

2022-09-06 15:17 UTC, manao-dev commented on Fw/Core/Page.php
> +        return '<link type="text/css" rel="stylesheet" href="' . $src . '">';
было бы не плохо добавить сюда символ переноса строки, чтобы не было всё в куче при выводе

2022-09-06 15:19 UTC, manao-dev commented on Fw/Core/Template.php
> +        include(__DIR__ . './../templates/' . self::$template . '/header.php');
даже визуально смотря на методы getHeader / getFooter хочется путь к шаблону проинициализировать в конструкторе

2022-09-06 15:20 UTC, manao-dev commented on Fw/Core/Template.php
> +    public function getFooter()
ещё момент, по неймингу
get - возвращает
set - устанавливает
add - добавляет
show - отображает
include / inc - подключает

2022-09-06 15:21 UTC, manao-dev commented on index.php
> +<pre>
ведём обратный поряд истории. Сверху всегда должны быть новые изменения

2022-09-06 15:22 UTC, manao-dev requested changes

2022-09-06 15:22 UTC, manao-dev commented on Fw/Core/Application.php
> +use Fw\Core\Traits\Single;
сингл трейт или как воспринимать такой нейминг?

2022-09-06 15:22 UTC, manao-dev commented on Fw/Core/Application.php
> +    private static $pager = null;
зачем $pager и $template статические?

2022-09-07 09:00 UTC, choco-cat commented on Fw/Core/Page.php
> +        echo "<$tag>$content</$tag>";
Удалила метод

2022-09-07 09:00 UTC, choco-cat commented on Fw/Core/Page.php
> +        $propertiesUnique = array_unique($this->headProperties[$key]);
Исправлено

2022-09-07 09:00 UTC, choco-cat commented on Fw/Core/Page.php
> +        return self::$properties[$id] ?? '';
Исправлено

2022-09-07 09:00 UTC, choco-cat commented on Fw/Core/Page.php
> +        return '<link type="text/css" rel="stylesheet" href="' . $src . '">';
Сделано

2022-09-07 09:01 UTC, choco-cat commented on Fw/Core/Template.php
> +        include(__DIR__ . './../templates/' . self::$template . '/header.php');
Сделано

2022-09-07 09:01 UTC, choco-cat commented on Fw/Core/Template.php
> +    public function getFooter()
Исправлено

2022-09-07 09:01 UTC, choco-cat commented on index.php
> +<pre>
Исправлено

2022-09-07 09:01 UTC, choco-cat commented on Fw/Core/Application.php
> +use Fw\Core\Traits\Single;
Исправлено

2022-09-07 09:02 UTC, choco-cat commented on Fw/Core/Application.php
> +    private static $pager = null;
Исправлено

2022-09-08 08:21 UTC, merged